services:
  backend:
    build: ./backend
    container_name: d-vhs-backend
    ports:
      - "8000:8000"
    # Wichtig: Nur das app-Verzeichnis mounten!
    volumes:
      - ./backend/app:/app/app
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: d-vhs-frontend
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
