version: "3.9"

services:
  backend:
    build: ./backend
    container_name: d-vhs-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: d-vhs-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package*.json:/app/
    depends_on:
      - backend
